import React from 'react';
import {
  FileText, ShieldCheck, Cookie, SlidersHorizontal, RotateCcw, Ban, Truck, PackageOpen,
  AlertTriangle, Accessibility, FileSignature, Gavel, Lock, Bug, Users, ChevronRight,
} from 'lucide-react';
import { PublicShell } from './PublicShell';
import { navigate } from '../../utils/publicRouter';

export interface LegalDoc {
  slug: string;
  title: string;
  icon: React.ReactNode;
  summary: string;
  sections: { heading: string; body: string[] }[];
}

const EFFECTIVE_DATE = 'August 31, 2026';

const shared = {
  identity: 'NEXSUS Security Operations Platform ("NEXSUS", "we", "us", or "our")',
};

export const LEGAL_DOCS: LegalDoc[] = [
  {
    slug: 'privacy-policy',
    title: 'Privacy Policy',
    icon: <ShieldCheck className="h-4 w-4" />,
    summary: 'What data NEXSUS collects during investigations, how it is used, and how operators can control it.',
    sections: [
      { heading: '1. Scope', body: [`This Privacy Policy explains how ${shared.identity} collects, uses, stores and shares information when you use the platform, including operator accounts, uploaded evidence artifacts, and telemetry generated by the specialist agent pipeline.`] },
      { heading: '2. Information We Collect', body: ['Account information (name, email, organization).', 'Case and investigation data you submit, including evidence artifacts, IOCs, and case notes.', 'Usage telemetry (feature interactions, session duration, error logs) used to keep the platform reliable.', 'AI provider configuration you supply — API keys are never persisted to our servers in plaintext and are stripped from client-side storage snapshots before export.'] },
      { heading: '3. How We Use Information', body: ['To operate, secure and improve the investigation pipeline.', 'To route evidence to the correct specialist agents and generate findings.', 'To communicate service, security, and billing notices.', 'We do not sell operator or case data to third parties.'] },
      { heading: '4. Data Retention', body: ['Case data is retained for the duration of your subscription plus any legally mandated retention period, after which it is deleted or anonymized upon request.'] },
      { heading: '5. Your Rights', body: ['Depending on your jurisdiction, you may have the right to access, correct, export, or delete your personal data. Contact privacy@nexsus.example to exercise these rights.'] },
      { heading: '6. Contact', body: ['Questions about this policy can be sent to privacy@nexsus.example.'] },
    ],
  },
  {
    slug: 'terms-of-service',
    title: 'Terms of Service',
    icon: <FileText className="h-4 w-4" />,
    summary: 'The agreement governing access to and use of the NEXSUS platform.',
    sections: [
      { heading: '1. Acceptance of Terms', body: [`By creating an account or using ${shared.identity}, you agree to be bound by these Terms of Service and our Privacy Policy.`] },
      { heading: '2. Use of the Platform', body: ['NEXSUS is provided for legitimate security investigation, incident response, and threat intelligence purposes only. You may not use the platform to analyze data you are not authorized to access, or to facilitate unlawful activity.'] },
      { heading: '3. Accounts', body: ['You are responsible for safeguarding your credentials and for all activity under your account. Notify us immediately of any unauthorized use.'] },
      { heading: '4. Subscriptions & Billing', body: ['Paid plans renew automatically until cancelled. See our Refund Policy and Cancellation Policy for details on billing disputes and plan changes.'] },
      { heading: '5. Disclaimers', body: ['Specialist agent findings and threat verdicts are generated by automated and AI-assisted analysis and are provided for investigative support — they do not constitute legal, forensic-certification, or professional advice. See our Disclaimer for full detail.'] },
      { heading: '6. Limitation of Liability', body: ['To the maximum extent permitted by law, NEXSUS is not liable for indirect, incidental, or consequential damages arising from use of the platform.'] },
      { heading: '7. Changes', body: ['We may update these Terms from time to time. Continued use after changes take effect constitutes acceptance.'] },
    ],
  },
  {
    slug: 'cookie-policy',
    title: 'Cookie Policy',
    icon: <Cookie className="h-4 w-4" />,
    summary: 'What cookies and local storage NEXSUS uses and why.',
    sections: [
      { heading: '1. What We Use', body: ['Strictly necessary: session/auth cookies required to keep you signed in.', 'Preference storage: theme, dashboard layout, and threat-threshold settings are stored in browser local storage on your device, not shared with third parties.', 'Analytics (optional): aggregated, anonymized usage metrics to improve reliability, only if you opt in.'] },
      { heading: '2. Managing Cookies', body: ['You can manage non-essential cookies at any time from Cookie Preferences. Strictly necessary cookies cannot be disabled without breaking sign-in.'] },
    ],
  },
  {
    slug: 'cookie-preferences',
    title: 'Cookie Preferences',
    icon: <SlidersHorizontal className="h-4 w-4" />,
    summary: 'Manage which optional cookies and analytics NEXSUS is allowed to use in this browser.',
    sections: [
      { heading: 'Strictly Necessary', body: ['Always on. Required for authentication and core platform functionality.'] },
      { heading: 'Preference Storage', body: ['Remembers your theme, dashboard layout, and emergency-threshold settings. Stored locally on this device.'] },
      { heading: 'Analytics', body: ['Off by default. When enabled, anonymized usage metrics help us prioritize reliability and feature work. Toggle this from Account Settings → Privacy at any time.'] },
    ],
  },
  {
    slug: 'refund-policy',
    title: 'Refund Policy',
    icon: <RotateCcw className="h-4 w-4" />,
    summary: 'When and how you can request a refund for a NEXSUS subscription.',
    sections: [
      { heading: '1. Eligibility', body: ['New subscriptions are eligible for a full refund within 14 days of the initial charge if the platform has not been used to process more than a nominal amount of evidence.'] },
      { heading: '2. Renewals', body: ['Renewal charges are refundable within 7 days of the renewal date upon request.'] },
      { heading: '3. How to Request', body: ['Submit a request from Billing → Cancel Subscription, or contact billing@nexsus.example. Approved refunds are returned to the original payment method within 5–10 business days.'] },
    ],
  },
  {
    slug: 'cancellation-policy',
    title: 'Cancellation Policy',
    icon: <Ban className="h-4 w-4" />,
    summary: 'How subscription cancellation works and what happens to your data afterward.',
    sections: [
      { heading: '1. Cancelling', body: ['You can cancel anytime from Billing → Cancel Subscription. Cancellation takes effect at the end of the current billing period; you retain access until then.'] },
      { heading: '2. After Cancellation', body: ['Case data and evidence artifacts remain accessible in a read-only export window for 30 days, after which they are scheduled for deletion unless you reactivate.'] },
    ],
  },
  {
    slug: 'shipping-policy',
    title: 'Shipping Policy',
    icon: <Truck className="h-4 w-4" />,
    summary: 'NEXSUS is a software service — this note covers the rare physical items we ship (hardware tokens, etc).',
    sections: [
      { heading: '1. Digital Service', body: ['NEXSUS is delivered entirely as a hosted/self-hosted software service. No physical shipment is required for standard subscriptions.'] },
      { heading: '2. Hardware Add-ons', body: ['Where optional hardware security keys are purchased through NEXSUS, they ship within 3–5 business days via tracked courier to the address on file, with tracking emailed on dispatch.'] },
    ],
  },
  {
    slug: 'returns-exchanges',
    title: 'Return / Exchange Policy',
    icon: <PackageOpen className="h-4 w-4" />,
    summary: 'Returns and exchanges for physical hardware add-ons purchased through NEXSUS.',
    sections: [
      { heading: '1. Hardware Add-ons', body: ['Unopened hardware security keys may be returned within 30 days of delivery for a full refund. Opened items may be exchanged for a defective-unit replacement only.'] },
      { heading: '2. How to Start a Return', body: ['Contact support@nexsus.example with your order number to receive a return authorization and shipping label.'] },
    ],
  },
  {
    slug: 'disclaimer',
    title: 'Disclaimer',
    icon: <AlertTriangle className="h-4 w-4" />,
    summary: 'The limits of automated and AI-assisted findings produced by the platform.',
    sections: [
      { heading: '1. No Professional Advice', body: ['Threat verdicts, malicious-score estimates, and specialist agent findings are generated by automated and AI-assisted analysis. They are decision-support tools and do not constitute legal, law-enforcement, or certified forensic advice.'] },
      { heading: '2. Human Review Required', body: ['High-impact actions (containment, disclosure, legal escalation) should always be reviewed by a qualified human analyst before being acted on.'] },
      { heading: '3. No Warranty', body: ['The platform is provided "as is" without warranty of completeness or fitness for a particular investigative outcome.'] },
    ],
  },
  {
    slug: 'accessibility-statement',
    title: 'Accessibility Statement',
    icon: <Accessibility className="h-4 w-4" />,
    summary: 'Our commitment to an accessible command center, and how to report issues.',
    sections: [
      { heading: '1. Our Commitment', body: ['We aim to meet WCAG 2.2 Level AA for core investigative workflows, including keyboard navigation, screen-reader labeling, and sufficient color contrast even under the Emergency Override theme.'] },
      { heading: '2. Known Limitations', body: ['Some data-dense visualizations (knowledge graph, threat map) offer a tabular fallback view; native chart accessibility improvements are ongoing.'] },
      { heading: '3. Reporting an Issue', body: ['If you encounter an accessibility barrier, contact accessibility@nexsus.example — we aim to acknowledge reports within 2 business days.'] },
    ],
  },
  {
    slug: 'data-processing-agreement',
    title: 'Data Processing Agreement',
    icon: <FileSignature className="h-4 w-4" />,
    summary: 'Terms governing NEXSUS as a data processor of your organization\'s case data (for enterprise/DPA-eligible plans).',
    sections: [
      { heading: '1. Roles', body: ['Where your organization submits personal data as part of case evidence, you act as the data controller and NEXSUS acts as data processor under applicable data protection law (e.g. GDPR Art. 28).'] },
      { heading: '2. Sub-processors', body: ['We maintain a current list of sub-processors (hosting, AI inference providers) available on request, and will notify enterprise customers of material changes.'] },
      { heading: '3. Security Measures', body: ['Encryption in transit and at rest, role-based access control, and audit logging are applied to processed case data. See our Security Policy for detail.'] },
      { heading: '4. Requesting a Signed DPA', body: ['Enterprise customers can request a countersigned DPA from legal@nexsus.example.'] },
    ],
  },
  {
    slug: 'acceptable-use-policy',
    title: 'Acceptable Use Policy',
    icon: <Gavel className="h-4 w-4" />,
    summary: 'What you may and may not do with the NEXSUS platform.',
    sections: [
      { heading: 'Prohibited Uses', body: ['Analyzing or storing data you are not legally authorized to access.', 'Using the platform to develop, test, or stage offensive malware against third parties.', 'Attempting to circumvent rate limits, authentication, or the specialist agent sandboxing.', 'Reselling or sublicensing platform access without authorization.'] },
      { heading: 'Enforcement', body: ['Violations may result in suspension or termination of access, and where required, disclosure to law enforcement.'] },
    ],
  },
  {
    slug: 'security-policy',
    title: 'Security Policy',
    icon: <Lock className="h-4 w-4" />,
    summary: 'How NEXSUS protects platform infrastructure and customer data.',
    sections: [
      { heading: '1. Infrastructure', body: ['Helmet-enforced security headers, strict Content-Security-Policy, CSRF protection, and rate limiting are applied across the API surface (see server.ts / server/security.ts).'] },
      { heading: '2. Secrets Handling', body: ['AI provider API keys are stripped before any client-side state is persisted or exported (see src/utils/security.ts) and are never logged.'] },
      { heading: '3. Access Control', body: ['Role-based access separates operator, analyst, and administrator capabilities. JWT-based sessions expire and require re-authentication (see Session Expired).'] },
      { heading: '4. Reporting a Vulnerability', body: ['See our Responsible Disclosure policy.'] },
    ],
  },
  {
    slug: 'responsible-disclosure',
    title: 'Responsible Disclosure',
    icon: <Bug className="h-4 w-4" />,
    summary: 'How to report a security vulnerability in NEXSUS responsibly.',
    sections: [
      { heading: '1. Reporting', body: ['Email security@nexsus.example with a description, reproduction steps, and impact assessment. Please do not publicly disclose before we have had a reasonable opportunity to remediate (target: 90 days).'] },
      { heading: '2. Safe Harbor', body: ['Good-faith research conducted within this policy will not result in legal action from NEXSUS. Avoid accessing, modifying, or deleting data that is not your own.'] },
      { heading: '3. Recognition', body: ['Valid reports may be credited in our security acknowledgments with your permission.'] },
    ],
  },
  {
    slug: 'community-guidelines',
    title: 'Community Guidelines',
    icon: <Users className="h-4 w-4" />,
    summary: 'Standards of conduct for shared cases, comments, and collaborative workspaces.',
    sections: [
      { heading: '1. Be Respectful', body: ['Treat fellow analysts and support staff professionally. Harassment, discrimination, or intimidation is not tolerated in case comments, chat, or support channels.'] },
      { heading: '2. Share Responsibly', body: ['Do not share raw customer PII or unredacted case evidence outside the workspace access controls configured by your organization.'] },
      { heading: '3. Reporting', body: ['Report violations to conduct@nexsus.example. Reports are reviewed by a human moderator, not an automated agent.'] },
    ],
  },
];

const LegalDocPage: React.FC<{ doc: LegalDoc }> = ({ doc }) => (
  <PublicShell title={doc.title} subtitle={`Effective ${EFFECTIVE_DATE} · ${doc.summary}`} backTo={{ label: 'All Legal Docs', href: '/legal' }}>
    <div className="space-y-6">
      {doc.sections.map((s) => (
        <section key={s.heading}>
          <h2 className="mb-2 font-cyber text-xs font-bold uppercase tracking-widest text-purple-300">{s.heading}</h2>
          <ul className="space-y-1.5">
            {s.body.map((line, i) => (
              <li key={i} className="font-mono text-[12px] leading-relaxed text-slate-300/90">{line}</li>
            ))}
          </ul>
        </section>
      ))}
      <p className="border-t border-purple-500/20 pt-4 font-mono text-[10px] text-purple-200/40">
        This document is a template provided for platform completeness and does not constitute legal advice. Have counsel review before relying on it.
      </p>
    </div>
  </PublicShell>
);

export const LegalHubPage: React.FC = () => (
  <PublicShell title="Legal & Compliance Center" subtitle="Every policy governing your use of NEXSUS, in one place." backTo={{ label: 'Back', href: '/' }}>
    <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
      {LEGAL_DOCS.map((doc) => (
        <button
          key={doc.slug}
          onClick={() => navigate(`/legal/${doc.slug}`)}
          className="group flex items-center justify-between gap-3 rounded-lg border border-purple-500/25 bg-purple-950/20 px-4 py-3 text-left transition-colors hover:border-purple-400/50 hover:bg-purple-500/10"
        >
          <span className="flex items-center gap-2.5">
            <span className="flex h-7 w-7 items-center justify-center rounded-md border border-purple-500/40 bg-purple-500/10 text-purple-300">{doc.icon}</span>
            <span className="font-mono text-[11px] uppercase tracking-wider text-slate-200">{doc.title}</span>
          </span>
          <ChevronRight className="h-3.5 w-3.5 text-purple-300/50 transition-transform group-hover:translate-x-0.5" />
        </button>
      ))}
    </div>
  </PublicShell>
);

export const LegalPage: React.FC<{ slug: string }> = ({ slug }) => {
  const doc = LEGAL_DOCS.find((d) => d.slug === slug);
  if (!doc) return <LegalHubPage />;
  return <LegalDocPage doc={doc} />;
};
