"""Professional, self-contained cybersecurity assessment PDF renderer."""

from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)


def battle_pdf(battle, responses, scores) -> bytes:
    out = BytesIO()
    doc = SimpleDocTemplate(
        out, pagesize=A4, rightMargin=42, leftMargin=42, topMargin=44, bottomMargin=42
    )
    styles = getSampleStyleSheet()
    title = ParagraphStyle(
        "title",
        parent=styles["Title"],
        textColor=colors.HexColor("#4c1d95"),
        fontSize=21,
        leading=25,
        alignment=TA_CENTER,
    )
    h = ParagraphStyle(
        "h",
        parent=styles["Heading2"],
        textColor=colors.HexColor("#5b21b6"),
        spaceBefore=13,
        spaceAfter=6,
    )
    body = ParagraphStyle("body", parent=styles["BodyText"], fontSize=8.5, leading=12)
    story = [
        Paragraph("CYBERSECURITY AI ANALYSIS", title),
        Spacer(1, 8),
        Paragraph("Confidential assessment generated by Nexsus", body),
        Spacer(1, 12),
    ]
    story += [
        Paragraph("Mission", h),
        Paragraph(f"<b>{battle.mission_type}</b><br/>{battle.task_description}", body),
    ]
    story += [
        Paragraph("Executive Summary", h),
        Paragraph(
            f"Winner: <b>{battle.winner_model or 'Pending judge'}</b> | Score: <b>{battle.winner_score or 'N/A'}</b>",
            body,
        ),
    ]
    story += [Paragraph("Model Comparison", h)]
    rows = [
        [
            "Model",
            "Score",
            "Accuracy",
            "Evidence",
            "Detection",
            "MITRE",
            "Recommendations",
        ]
    ]
    for s in scores:
        rows.append(
            [
                f"{s.provider}:{s.model}",
                f"{s.total_score:.1f}",
                f"{s.accuracy:.0f}",
                f"{s.evidence:.0f}",
                f"{s.detection_accuracy:.0f}",
                f"{s.mitre_accuracy:.0f}",
                f"{s.recommendation_quality:.0f}",
            ]
        )
    table = Table(
        rows,
        repeatRows=1,
        colWidths=[
            1.5 * inch,
            0.55 * inch,
            0.58 * inch,
            0.58 * inch,
            0.62 * inch,
            0.52 * inch,
            0.75 * inch,
        ],
    )
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4c1d95")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#d8b4fe")),
                ("FONT", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 7.5),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                (
                    "ROWBACKGROUNDS",
                    (0, 1),
                    (-1, -1),
                    [colors.white, colors.HexColor("#faf5ff")],
                ),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    story.append(table)
    story += [Paragraph("AI Judge Results", h)]
    for s in scores:
        story.append(
            Paragraph(
                f"<b>{s.provider}:{s.model}</b> - {s.judge_reasoning or 'No judge explanation available.'}",
                body,
            )
        )
        story.append(Spacer(1, 4))
    story += [PageBreak(), Paragraph("Findings and Model Responses", h)]
    for r in responses:
        story += [
            Paragraph(f"{r.provider}:{r.model} ({r.status})", h),
            Paragraph(
                (r.content or r.error or "No result")
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace("\n", "<br/>"),
                body,
            ),
        ]
    doc.build(story)
    return out.getvalue()
