"use client";
import { useEffect, useState } from "react";
import { DashboardShell } from "@/components/layout/DashboardShell";
import { apiGet, apiPost, apiUrl } from "@/lib/api";
type M={provider:string;model:string}; type R=M&{id:string;content:string;status:string;error?:string;latency_ms?:number};
export default function BattleModePage(){
 const [mission,setMission]=useState("malware_analysis"),[task,setTask]=useState("Analyze this evidence for IOCs, behavior, MITRE ATT&CK and mitigations."),[models,setModels]=useState<M[]>([]),[catalog,setCatalog]=useState<M[]>([]),[choice,setChoice]=useState(""),[id,setId]=useState(""),[files,setFiles]=useState<string[]>([]),[rs,setRs]=useState<R[]>([]),[scores,setScores]=useState<any[]>([]),[run,setRun]=useState(false),[err,setErr]=useState("");
 useEffect(()=>{apiGet<any[]>("/providers/models/all").then(x=>{const c=x.data.flatMap((p:any)=>(p.models||[]).map((m:any)=>({provider:p.provider,model:m.id})));setCatalog(c);setChoice(c[0]?`${c[0].provider}:${c[0].model}`:"")}).catch(()=>{})},[]);
 useEffect(()=>{if(!id||!run)return;const es=new EventSource(apiUrl(`/battle/${id}/stream`));es.onmessage=async e=>{const x=JSON.parse(e.data);if(x.type==="model_token")setRs(a=>a.map(r=>r.id===x.response_id?{...r,content:x.content,status:"streaming"}:r));if(x.type==="model_completed"||x.type==="model_error")setRs(a=>a.map(r=>r.id===x.response_id?{...r,...x,status:x.type==="model_error"?"error":"completed"}:r));if(x.type==="model_stopped")setRs(a=>a.map(r=>r.id===x.response_id?{...r,content:x.content,status:"stopped"}:r));if(x.type==="run_completed"){setRun(false);es.close();try{const j=await apiPost<any>(`/battle/${id}/judge`);setScores(j.data.scores)}catch(e:any){setErr(e.message)}}};return()=>es.close()},[id,run]);
 const add=()=>{const [provider,...rest]=choice.split(":");const model=rest.join(":");if(provider&&models.length<8&&!models.some(x=>x.provider===provider&&x.model===model))setModels([...models,{provider,model}])};
 async function attach(f?:File){if(!f)return;const form=new FormData();form.append("file",f);try{const r=await fetch(apiUrl("/files/analyze"),{method:"POST",body:form});const x=await r.json();if(!r.ok)throw Error(x.message);setFiles(v=>[...v,x.data.id])}catch(e:any){setErr(e.message)}}
 async function start(){try{const b=await apiPost<any>("/battle",{name:`${mission} battle`,mission_type:mission,task_description:task,model_configs:models,file_ids:files});const x=await apiPost<any>(`/battle/${b.data.id}/run`);setId(b.data.id);setRs(models.map((m,i)=>({...m,id:String(x.data.response_ids[i]),content:"",status:"streaming"})));setScores([]);setRun(true)}catch(e:any){setErr(e.message)}}
 async function stop(){if(!id)return;await apiPost(`/battle/${id}/stop`);setRun(false);setRs(a=>a.map(r=>r.status==="streaming"?{...r,status:"stopped"}:r))}
 return (
  <DashboardShell>
   <main className="mx-auto max-w-7xl space-y-5 p-2">
    <header><p className="text-xs tracking-[.25em] text-violet-400">CYBERSECURITY MODEL EVALUATION</p><h1 className="text-3xl font-semibold">AI Battle Mode</h1></header>{err&&<p className="text-red-300">{err}</p>}<section className="panel space-y-3 p-4"><select value={mission} onChange={e=>setMission(e.target.value)} className="rounded bg-black/30 p-2"><option value="malware_analysis">Malware analysis</option><option value="phishing_analysis">Phishing analysis</option><option value="code_review">Secure code review</option></select><textarea value={task} onChange={e=>setTask(e.target.value)} className="min-h-32 w-full rounded bg-black/30 p-3"/><label className="block text-xs">Evidence (stored safely; never executed)<input type="file" className="block" onChange={e=>attach(e.target.files?.[0])}/></label><div className="flex gap-2"><select value={choice} onChange={e=>setChoice(e.target.value)} className="rounded bg-black/30 p-2">{catalog.map(x=><option key={x.provider+x.model} value={`${x.provider}:${x.model}`}>{x.provider}:{x.model}</option>)}</select><button className="rounded bg-violet-600 px-3" onClick={add}>Add model</button><button disabled={run||models.length<2} onClick={start} className="rounded bg-violet-600 px-4 disabled:opacity-40">Start battle</button>{run&&<button onClick={stop} className="rounded border border-red-400/60 px-4 text-red-200">Stop</button>}{id&&<a href={apiUrl(`/battle/${id}/export?format=pdf`)} className="rounded border px-3">PDF report</a>}</div>{models.map(x=><div key={x.provider+x.model} className="flex justify-between text-sm"><span>{x.provider}:{x.model}</span><button onClick={()=>setModels(models.filter(y=>y!==x))}>Remove</button></div>)}</section><section className="grid gap-4 md:grid-cols-2">{rs.map(r=><article key={r.id} className="panel"><div className="panel-header"><b>{r.provider}:{r.model}</b><span>{r.status==="error"?`Error: ${r.error}`:r.status}</span></div><pre className="min-h-32 whitespace-pre-wrap p-3 text-xs">{r.content||"Waiting for provider..."}</pre></article>)}</section>{scores.length>0&&<section className="panel p-4"><h2 className="panel-title">AI judge scorecard</h2>{scores.sort((a,b)=>b.total_score-a.total_score).map((s,i)=><div key={s.provider+s.model} className="mt-3 rounded border border-violet-500/20 p-3"><b>{i===0?"Winner: ":""}{s.provider}:{s.model} - {s.total_score.toFixed(1)}/100</b><p className="text-xs">Accuracy {s.accuracy} | Depth {s.depth} | Actionability {s.actionability} | Evidence {s.evidence} | IOC Precision {s.ioc_precision} | IOC Recall {s.ioc_recall} | MITRE {s.mitre_accuracy} | Detection {s.detection_accuracy} | Recommendations {s.recommendation_quality} | Speed {s.speed}</p></div>)}</section>}
   </main>
  </DashboardShell>
 );
}
